---
kind: Application
name: sw4iot-iot-appserver
services:
  mongo1:
    gateway: host
    image: mongo:latest
    container_name: db-mongo11
  mongo2:
    gateway: 4
    image: mongo:latest
    container_name: db-mongo22
