---
kind: Application
name: multiploscontainershost
services:
  mongo:
    container_name: mongo1
    image: mongo:latest
    gateway: host
    
  ubuntu:
    container_name: mongo2
    image: mongo:latest
    gateway: host
