---
kind: Application
name: multiploscontainers
services:
  mongo:
    container_name: mongo1
    image: mongo:latest
    gateway: host
    
  ubuntu:
    container_name: ubuntu1
    image: ubuntu:latest
    gateway: host
